### ISSUE TITLE
i watch this

### ISSUE THREAD

**Issue by mygoda** [genti-t/b-kube#1]
thank you for your project,and i expect that doc come on. do you also have some course to let us create a HA kubernetes cluster with more master node and more node,also with extra etcd cluster. thank you.

**Comment by genti-t** [comment]
Yes, the idea on this project is especially that. Having at least 3 Kubernetes controller nodes, a dedicated etcd cluster and as many worker nodes as you want.  
All will be more clear when the first release will be concluded, next month (probably).

**Comment by mygoda** [comment]
@genti-t  ok. now i have a simple idea, i have create a watch dog project. this project watching master schedule, controller status by get /health. and keep only one do work. when he catch 0 work, this dog can random start one.

**Comment by genti-t** [comment]
@mygoda The HA part for the controllers component is solved with --leader-election.
Here I have implemented Keeapalived and HAProxy on controllers nodes, for the kublet and proxy to point to, until  [#30588](https://github.com/kubernetes/kubernetes/pull/30588) is solved.

**Comment by mygoda** [comment]
@genti-t  thankyou. and when i catch new problem, i hope that you help me again. thanks.
